name: our workflow for the Image-recommender project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Main-CI:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
          choco install cmake
          pip install .
          pip install matplotlib --prefer-binary

      - name: Install dependencies on other OSes
        if: matrix.os != 'windows-latest'
        run: pip install .

      - name: lint with ruff
        run: |
          ruff resources/.

      - name: test with pytest
        run: |
          pytest -v
